/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ControllerUsuario;
import model.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class FrmCadUser extends javax.swing.JInternalFrame {
    ControllerUsuario controlUser = new ControllerUsuario();
    List<Usuario> listUsuario = controlUser.recarregarLista();
    int indice = 0;
    
    public FrmCadUser() {
        initComponents();
        atualizarBotoes();
        if (! listUsuario.isEmpty()) {
            preencherTabela();
            mostrarDadosTela(indice);
        }
        tabUsuarios.changeSelection(indice, 1, false, false);
    }
    
    private void mostrarDadosTela(int i) {
        if (listUsuario.isEmpty()) {
            txtId.setText("");
            txtNome.setText("");
            txtSenha.setText("");
            txtEmail.setText("");
            groupTipo.clearSelection();
        } 
        else {
            txtId.setText(""+listUsuario.get(i).id);
            txtNome.setText(listUsuario.get(i).nome);
            txtSenha.setText(listUsuario.get(i).senha);
            txtEmail.setText(listUsuario.get(i).email);
            var tipo = listUsuario.get(i).tipo == 1 ? radioAdmin.getModel() : radioComum.getModel();
            groupTipo.setSelected(tipo, true);
        }
    }
    
    private void atualizarBotoes() {
        btnPrevious.setEnabled(indice>0);
        btnFirst.setEnabled(indice>0);

        btnNext.setEnabled(indice<listUsuario.size()-1);
        btnLast.setEnabled(indice<listUsuario.size()-1);
        
        btnRemover.setEnabled(indice!=-1);
        btnEditar.setEnabled(indice!=-1);
    }
    
    private void preencherTabela() {
        
        DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer();
	cellRender.setHorizontalAlignment(SwingConstants.CENTER);
        tabUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);  //Preferencia de largura medidad em pixels
        tabUsuarios.getColumnModel().getColumn(1).setPreferredWidth(80);  
        tabUsuarios.getColumnModel().getColumn(2).setPreferredWidth(50);  
        tabUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabUsuarios.getColumnModel().getColumn(4).setPreferredWidth(10);
        for (int i=0; i<tabUsuarios.getColumnCount(); i++)
            tabUsuarios.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        
        DefaultTableModel modelo = (DefaultTableModel) tabUsuarios.getModel();
        modelo.setNumRows(0);
        for (Usuario user: listUsuario) {
            modelo.addRow(new Object[]{
                user.id, 
                user.nome, 
                user.senha, 
                user.email,
                user.tipo});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipo = new javax.swing.ButtonGroup();
        txtNome = new javax.swing.JTextField();
        lblCadTitulo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblErro = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        scrollTabela = new javax.swing.JScrollPane();
        tabUsuarios = new javax.swing.JTable();
        txtSenha = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radioAdmin = new javax.swing.JRadioButton();
        radioComum = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(122, 225, 227));
        setClosable(true);
        setIconifiable(true);
        setTitle("Gerenciar Usuarios");

        txtNome.setBackground(new java.awt.Color(204, 255, 255));
        txtNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        lblCadTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblCadTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadTitulo.setText("Gerenciar Usuários");

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(204, 255, 255));
        txtId.setToolTipText("");
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        btnSalvar.setBackground(new java.awt.Color(204, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 153, 153));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/floppy_disk16x16.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(204, 255, 255));
        btnEditar.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(0, 153, 153));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit16x16.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblErro.setForeground(new java.awt.Color(255, 0, 51));

        btnRemover.setBackground(new java.awt.Color(204, 255, 255));
        btnRemover.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(0, 153, 153));
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/garbage_can.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(204, 255, 255));
        btnFirst.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(204, 255, 255));
        btnLast.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(204, 255, 255));
        btnPrevious.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnPrevious.setText("<<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(204, 255, 255));
        btnNext.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        scrollTabela.setBackground(new java.awt.Color(255, 255, 204));
        scrollTabela.setForeground(new java.awt.Color(0, 204, 204));
        scrollTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "SENHA", "EMAIL", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabUsuarios.setShowGrid(false);
        tabUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabUsuariosMouseClicked(evt);
            }
        });
        tabUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabUsuariosKeyReleased(evt);
            }
        });
        scrollTabela.setViewportView(tabUsuarios);

        txtSenha.setBackground(new java.awt.Color(204, 255, 255));
        txtSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SENHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        txtEmail.setBackground(new java.awt.Color(204, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMAIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        radioAdmin.setBackground(new java.awt.Color(204, 255, 255));
        groupTipo.add(radioAdmin);
        radioAdmin.setForeground(new java.awt.Color(0, 153, 153));
        radioAdmin.setText("Administrador");
        radioAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/businessman.png"))); // NOI18N
        radioAdmin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/businessmanB.png"))); // NOI18N

        radioComum.setBackground(new java.awt.Color(204, 255, 255));
        groupTipo.add(radioComum);
        radioComum.setForeground(new java.awt.Color(0, 153, 153));
        radioComum.setText("Comum");
        radioComum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        radioComum.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(radioComum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioAdmin)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioComum)
                .addComponent(radioAdmin))
        );

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(lblCadTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCadTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemover)
                            .addComponent(btnSalvar)
                            .addComponent(btnEditar)))
                    .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Usuario user = new Usuario();
        
        user.nome = txtNome.getText();
        user.senha = String.valueOf(txtSenha.getPassword());
        user.email = txtEmail.getText().toLowerCase();
        user.tipo = groupTipo.getSelection() == radioComum.getModel() ? 2 :
                (groupTipo.getSelection() == radioAdmin.getModel() ? 1 : 0);
        if (user.tipo == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um tipo de usuário", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }         
        
        listUsuario = controlUser.recarregarLista();
        JOptionPane.showMessageDialog(this, "Usuario salvo\nId: "+listUsuario.get(listUsuario.size()-1).id+"\nNome: "+user.nome+"\nemail: "+user.email+"\nTipo: "+user.tipo);
        
        indice = listUsuario.size()-1;
        mostrarDadosTela(indice);
        preencherTabela();
        tabUsuarios.changeSelection(indice, 1, false, false);
        atualizarBotoes();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        Usuario user = new Usuario();
        user.id = Integer.parseInt(txtId.getText());
        user.nome = txtNome.getText();
        user.senha = String.valueOf(txtSenha.getPassword());
        user.email = txtEmail.getText().toLowerCase();
        user.tipo = groupTipo.getSelection() == radioComum.getModel() ? 2 :
                (groupTipo.getSelection() == radioAdmin.getModel() ? 1 : 0);
        
        controlUser.atualizarUsuario(user);
        
        listUsuario = controlUser.recarregarLista();
        preencherTabela();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        int id = Integer.parseInt(txtId.getText());
        controlUser.deletarUsuario(id);
        
        indice += indice>0 ? -1 : (listUsuario.isEmpty() ? -1 : +0);
        listUsuario = controlUser.recarregarLista();
        mostrarDadosTela(indice);
        preencherTabela();
        tabUsuarios.changeSelection(indice, 1, false, false);
        atualizarBotoes();
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        indice = 0;
        mostrarDadosTela(indice);
        tabUsuarios.changeSelection(indice, 1, false, false);
        atualizarBotoes();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        indice = listUsuario.size()-1;
        mostrarDadosTela(indice);
        tabUsuarios.changeSelection(indice, 1, false, false);
        atualizarBotoes();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        mostrarDadosTela(--indice);
        tabUsuarios.changeSelection(indice, 1, false, false);
        atualizarBotoes();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        mostrarDadosTela(++indice);
        tabUsuarios.changeSelection(indice, 1, false, false);
        atualizarBotoes();
    }//GEN-LAST:event_btnNextActionPerformed

    private void tabUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabUsuariosKeyReleased
        indice = tabUsuarios.getSelectedRow();
        mostrarDadosTela(indice);
        atualizarBotoes();
    }//GEN-LAST:event_tabUsuariosKeyReleased

    private void tabUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUsuariosMouseClicked
        indice = tabUsuarios.getSelectedRow();
        mostrarDadosTela(indice);
        atualizarBotoes();
    }//GEN-LAST:event_tabUsuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtId.setText("");
        txtNome.setText("");
        txtSenha.setText("");
        txtEmail.setText("");
        groupTipo.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup groupTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadTitulo;
    private javax.swing.JLabel lblErro;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioComum;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JTable tabUsuarios;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
