
package view;

public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }
    public FrmMenuPrincipal(int status) {
        initComponents();
        if (status!=1){
            mniCadUsuario.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        lblIcone = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAcoes = new javax.swing.JMenu();
        mniCadCidade = new javax.swing.JMenuItem();
        mniCadUsuario = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cidades");
        setBackground(new java.awt.Color(0, 204, 204));

        jDesktopPanePrincipal.setBackground(new java.awt.Color(204, 255, 255));

        lblIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cityBlueLogo.png"))); // NOI18N

        jDesktopPanePrincipal.setLayer(lblIcone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(lblIcone, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanePrincipalLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblIcone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        menuAcoes.setBorder(null);
        menuAcoes.setText("Ações ");
        menuAcoes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        menuAcoes.setPreferredSize(new java.awt.Dimension(50, 20));

        mniCadCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniCadCidade.setText("Cadastrar cidade");
        mniCadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadCidadeActionPerformed(evt);
            }
        });
        menuAcoes.add(mniCadCidade);

        mniCadUsuario.setText("Gerenciar usuários");
        mniCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadUsuarioActionPerformed(evt);
            }
        });
        menuAcoes.add(mniCadUsuario);

        jMenuBar1.add(menuAcoes);

        menuSair.setBorder(null);
        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void mniCadCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadCidadeActionPerformed
        FrmCadCidade Cadastrar = new FrmCadCidade();
        jDesktopPanePrincipal.add(Cadastrar);
        Cadastrar.setVisible(true);
    }//GEN-LAST:event_mniCadCidadeActionPerformed

    private void mniCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadUsuarioActionPerformed
        FrmCadUser cadUser = new FrmCadUser();
        jDesktopPanePrincipal.add(cadUser);
        cadUser.setVisible(true);
    }//GEN-LAST:event_mniCadUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblIcone;
    private javax.swing.JMenu menuAcoes;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem mniCadCidade;
    private javax.swing.JMenuItem mniCadUsuario;
    // End of variables declaration//GEN-END:variables
}
